# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(default='TITLE', verbose_name='题目')),
                ('options', models.TextField(default='OPTIONS', verbose_name='选项')),
                ('answer', models.CharField(default='A', max_length=32, verbose_name='答案')),
                ('subjctNumber', models.IntegerField(default=0, verbose_name='课程号')),
                ('subjct', models.CharField(default='SUBJECT', max_length=32, verbose_name='课程名称')),
                ('difficultyDegree', models.IntegerField(default=1, verbose_name='难度系数')),
                ('pub_time', models.DateTimeField(null=True, verbose_name='收录时间')),
            ],
        ),
    ]
