# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 05:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Teacher',
        ),
    ]
