# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='username',
            new_name='name',
        ),
        migrations.AddField(
            model_name='student',
            name='attendance_year',
            field=models.CharField(default='2013', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.CharField(default='计算机', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.CharField(default='华侨大学', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_number',
            field=models.CharField(default=1325113030, max_length=50),
            preserve_default=False,
        ),
    ]
