# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0011_auto_20170403_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisehistory',
            name='subject',
            field=models.CharField(max_length=20, null=True, verbose_name='科目'),
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.CharField(default='计算机', max_length=50, null=True, verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=50, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(default='华侨大学', max_length=50, null=True, verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.CharField(max_length=50, verbose_name='学号'),
        ),
    ]
